apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalineage-api.fullname" . }}
  labels: {{- include "datalineage-api.labels" . | nindent 4 }}
spec:
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ include "datalineage-api.fullname" . }}
