# Base Image
FROM docker.repo-ci.sfera.inno.local/sumd-docker-lib/ubi8-base-data-lineage-ui:v1.0.2 as build-deps

# build react-client
COPY . ./
RUN npm run build

# Phase 2 - Get the Build and host on nginx
FROM docker.repo-ci.sfera.inno.local/sumd-docker-lib/nginx:1.20.2
COPY --from=build-deps /app/dist /usr/share/nginx/html
# COPY app/template /usr/share/nginx/html/template
COPY default.conf /etc/nginx/conf.d/default.conf
RUN chgrp -R root /var/cache/nginx /var/run /var/log/nginx && \
    chmod -R 770 /var/cache/nginx /var/run /var/log/nginx
EXPOSE 8080

# Start up command
CMD ["nginx", "-g", "daemon off;"]