# Default values for data-lineage-api.

pullSecret: ci-dos

replicaCount: 1

image:
  repository: nexus-ci.corp.dev.vtb/sumd-docker-lib/data-lineage-api
  tag: v1.0.0
  pullPolicy: Always

resources:
  requests:
    cpu: "1000m"
    memory: "2000Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"

secretName: ingress-tls

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: data-lineage-api-ds1-lpad01-sumd-team-sumcore-system.apps.ds1-lpad01.corp.dev.vtb
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: data-lineage-api
              port:
                number: 3000
  tls:
    - secretName: ingress-tls
      hosts:
        - data-lineage-api-ds1-lpad01-sumd-team-sumcore-system.apps.ds1-lpad01.corp.dev.vtb


###Выбор worker ноды без GPU
affinity:
  enabled: false
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: nvidia.com/gpu.product
#              operator: DoesNotExist

### Выбор политики для автоскалирования количества подов - разкомментить требуемое
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetCPUAverageValue: 100m
  # targetMemoryUtilizationPercentage: 80
  # targetMemoryAverageValue: 200Mi

secrets:
  immutable:
    enabled: false

env:
 DB_HOST: d5sumd-pgc001lk.corp.dev.vtb
 DB_PORT: 5432
 DB_NAME: data_lineage
 NODE_ENV: production
 KEYCLOAK_URL: https://keycloak-sumd.sumd.dk1-sumd01.innodev.local/auth/
 KEYCLOAK_REALM: cym
 KEYCLOAK_CLIENT: frontend
 NODE_TLS_REJECT_UNAUTHORIZED: 0
 PORT: 3000

secret:
 DB_USERNAME: "data_lineage_admin"
 DB_PASSWORD: "sum_user_pass"
 SESSION_SECRET: "my-secret"
