export const DEFAULT_STRINGIFIED_JSON: string = JSON.stringify(
	{
		_id: "67ec5ff72fc962d03a0a6299",
		index: 0,
		guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
		isActive: true,
		balance: "$3,864.93",
		picture: "http://placehold.it/32x32",
		age: 39,
		eyeColor: "green",
		name: "Kerri Delaney",
		gender: "female",
		company: "PLASMOSIS",
		email: "kerridelaney@plasmosis.com",
		phone: "+1 (834) 413-3068",
		address: "310 Kings Hwy, Avoca, Virginia, 9799",
		about:
			"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
		registered: "2020-05-05T06:09:18 -03:00",
		latitude: 50.284115,
		longitude: -113.427339,
		tags: [
			"dolor",
			"fugiat",
			"voluptate",
			"ipsum",
			"commodo",
			"ullamco",
			"excepteur",
		],
		friends: [
			{
				id: 0,
				name: "Dawn Britt",
			},
			{
				id: 1,
				name: "Miles Gross",
			},
			{
				id: 2,
				name: {
					_id: "67ec5ff72fc962d03a0a6299",
					index: 0,
					guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
					isActive: true,
					balance: "$3,864.93",
					picture: "http://placehold.it/32x32",
					age: 39,
					eyeColor: "green",
					name: "Kerri Delaney",
					gender: "female",
					company: "PLASMOSIS",
					email: "kerridelaney@plasmosis.com",
					phone: "+1 (834) 413-3068",
					address: "310 Kings Hwy, Avoca, Virginia, 9799",
					about:
						"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
					registered: "2020-05-05T06:09:18 -03:00",
					latitude: 50.284115,
					longitude: -113.427339,
					tags: [
						"dolor",
						"fugiat",
						"voluptate",
						"ipsum",
						"commodo",
						"ullamco",
						"excepteur",
					],
					friends: [
						{
							id: 0,
							name: "Dawn Britt",
						},
						{
							id: 1,
							name: "Miles Gross",
						},
						{
							id: 2,
							name: "Rachael Cantu",
						},
					],
					greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
					favoriteFruit: {
						_id: "67ec5ff72fc962d03a0a6299",
						index: 0,
						guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
						isActive: true,
						balance: "$3,864.93",
						picture: "http://placehold.it/32x32",
						age: 39,
						eyeColor: "green",
						name: "Kerri Delaney",
						gender: "female",
						company: "PLASMOSIS",
						email: "kerridelaney@plasmosis.com",
						phone: "+1 (834) 413-3068",
						address: "310 Kings Hwy, Avoca, Virginia, 9799",
						about:
							"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
						registered: "2020-05-05T06:09:18 -03:00",
						latitude: 50.284115,
						longitude: -113.427339,
						tags: [
							"dolor",
							"fugiat",
							"voluptate",
							"ipsum",
							"commodo",
							"ullamco",
							"excepteur",
						],
						friends: [
							{
								id: 0,
								name: "Dawn Britt",
							},
							{
								id: 1,
								name: "Miles Gross",
							},
							{
								id: 2,
								name: "Rachael Cantu",
							},
						],
						greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
						favoriteFruit: "banana",
					},
				},
			},
		],
		greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
		favoriteFruit: {
			_id: "67ec5ff72fc962d03a0a6299",
			index: 0,
			guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
			isActive: true,
			balance: "$3,864.93",
			picture: "http://placehold.it/32x32",
			age: 39,
			eyeColor: "green",
			name: "Kerri Delaney",
			gender: "female",
			company: "PLASMOSIS",
			email: "kerridelaney@plasmosis.com",
			phone: "+1 (834) 413-3068",
			address: "310 Kings Hwy, Avoca, Virginia, 9799",
			about:
				"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
			registered: "2020-05-05T06:09:18 -03:00",
			latitude: 50.284115,
			longitude: -113.427339,
			tags: [
				"dolor",
				"fugiat",
				"voluptate",
				"ipsum",
				"commodo",
				"ullamco",
				"excepteur",
			],
			friends: [
				{
					id: 0,
					name: "Dawn Britt",
				},
				{
					id: 1,
					name: "Miles Gross",
				},
				{
					id: 2,
					name: {
						_id: "67ec5ff72fc962d03a0a6299",
						index: 0,
						guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
						isActive: true,
						balance: "$3,864.93",
						picture: "http://placehold.it/32x32",
						age: 39,
						eyeColor: "green",
						name: "Kerri Delaney",
						gender: "female",
						company: "PLASMOSIS",
						email: "kerridelaney@plasmosis.com",
						phone: "+1 (834) 413-3068",
						address: "310 Kings Hwy, Avoca, Virginia, 9799",
						about:
							"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
						registered: "2020-05-05T06:09:18 -03:00",
						latitude: 50.284115,
						longitude: -113.427339,
						tags: [
							"dolor",
							"fugiat",
							"voluptate",
							"ipsum",
							"commodo",
							"ullamco",
							"excepteur",
						],
						friends: [
							{
								id: 0,
								name: "Dawn Britt",
							},
							{
								id: 1,
								name: "Miles Gross",
							},
							{
								id: 2,
								name: "Rachael Cantu",
							},
						],
						greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
						favoriteFruit: {
							_id: "67ec5ff72fc962d03a0a6299",
							index: 0,
							guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
							isActive: true,
							balance: "$3,864.93",
							picture: "http://placehold.it/32x32",
							age: 39,
							eyeColor: "green",
							name: "Kerri Delaney",
							gender: "female",
							company: "PLASMOSIS",
							email: "kerridelaney@plasmosis.com",
							phone: "+1 (834) 413-3068",
							address: "310 Kings Hwy, Avoca, Virginia, 9799",
							about:
								"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
							registered: "2020-05-05T06:09:18 -03:00",
							latitude: 50.284115,
							longitude: -113.427339,
							tags: [
								"dolor",
								"fugiat",
								"voluptate",
								"ipsum",
								"commodo",
								"ullamco",
								"excepteur",
							],
							friends: [
								{
									id: 0,
									name: "Dawn Britt",
								},
								{
									id: 1,
									name: "Miles Gross",
								},
								{
									id: 2,
									name: "Rachael Cantu",
								},
							],
							greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
							favoriteFruit: "banana",
						},
					},
				},
			],
			greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
			favoriteFruit: {
				_id: "67ec5ff72fc962d03a0a6299",
				index: 0,
				guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
				isActive: true,
				balance: "$3,864.93",
				picture: "http://placehold.it/32x32",
				age: 39,
				eyeColor: "green",
				name: "Kerri Delaney",
				gender: "female",
				company: "PLASMOSIS",
				email: "kerridelaney@plasmosis.com",
				phone: "+1 (834) 413-3068",
				address: "310 Kings Hwy, Avoca, Virginia, 9799",
				about:
					"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
				registered: "2020-05-05T06:09:18 -03:00",
				latitude: 50.284115,
				longitude: -113.427339,
				tags: [
					"dolor",
					"fugiat",
					"voluptate",
					"ipsum",
					"commodo",
					"ullamco",
					"excepteur",
				],
				friends: [
					{
						id: 0,
						name: "Dawn Britt",
					},
					{
						id: 1,
						name: "Miles Gross",
					},
					{
						id: 2,
						name: {
							_id: "67ec5ff72fc962d03a0a6299",
							index: 0,
							guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
							isActive: true,
							balance: "$3,864.93",
							picture: "http://placehold.it/32x32",
							age: 39,
							eyeColor: "green",
							name: "Kerri Delaney",
							gender: "female",
							company: "PLASMOSIS",
							email: "kerridelaney@plasmosis.com",
							phone: "+1 (834) 413-3068",
							address: "310 Kings Hwy, Avoca, Virginia, 9799",
							about:
								"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
							registered: "2020-05-05T06:09:18 -03:00",
							latitude: 50.284115,
							longitude: -113.427339,
							tags: [
								"dolor",
								"fugiat",
								"voluptate",
								"ipsum",
								"commodo",
								"ullamco",
								"excepteur",
							],
							friends: [
								{
									id: 0,
									name: "Dawn Britt",
								},
								{
									id: 1,
									name: "Miles Gross",
								},
								{
									id: 2,
									name: "Rachael Cantu",
								},
							],
							greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
							favoriteFruit: {
								_id: "67ec5ff72fc962d03a0a6299",
								index: 0,
								guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
								isActive: true,
								balance: "$3,864.93",
								picture: "http://placehold.it/32x32",
								age: 39,
								eyeColor: "green",
								name: "Kerri Delaney",
								gender: "female",
								company: "PLASMOSIS",
								email: "kerridelaney@plasmosis.com",
								phone: "+1 (834) 413-3068",
								address: "310 Kings Hwy, Avoca, Virginia, 9799",
								about:
									"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
								registered: "2020-05-05T06:09:18 -03:00",
								latitude: 50.284115,
								longitude: -113.427339,
								tags: [
									"dolor",
									"fugiat",
									"voluptate",
									"ipsum",
									"commodo",
									"ullamco",
									"excepteur",
								],
								friends: [
									{
										id: 0,
										name: "Dawn Britt",
									},
									{
										id: 1,
										name: "Miles Gross",
									},
									{
										id: 2,
										name: "Rachael Cantu",
									},
								],
								greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
								favoriteFruit: "banana",
							},
						},
					},
				],
				greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
				favoriteFruit: {
					_id: "67ec5ff72fc962d03a0a6299",
					index: 0,
					guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
					isActive: true,
					balance: "$3,864.93",
					picture: "http://placehold.it/32x32",
					age: 39,
					eyeColor: "green",
					name: "Kerri Delaney",
					gender: "female",
					company: "PLASMOSIS",
					email: "kerridelaney@plasmosis.com",
					phone: "+1 (834) 413-3068",
					address: "310 Kings Hwy, Avoca, Virginia, 9799",
					about:
						"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
					registered: "2020-05-05T06:09:18 -03:00",
					latitude: 50.284115,
					longitude: -113.427339,
					tags: [
						"dolor",
						"fugiat",
						"voluptate",
						"ipsum",
						"commodo",
						"ullamco",
						"excepteur",
					],
					friends: [
						{
							id: 0,
							name: "Dawn Britt",
						},
						{
							id: 1,
							name: "Miles Gross",
						},
						{
							id: 2,
							name: {
								_id: "67ec5ff72fc962d03a0a6299",
								index: 0,
								guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
								isActive: true,
								balance: "$3,864.93",
								picture: "http://placehold.it/32x32",
								age: 39,
								eyeColor: "green",
								name: "Kerri Delaney",
								gender: "female",
								company: "PLASMOSIS",
								email: "kerridelaney@plasmosis.com",
								phone: "+1 (834) 413-3068",
								address: "310 Kings Hwy, Avoca, Virginia, 9799",
								about:
									"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
								registered: "2020-05-05T06:09:18 -03:00",
								latitude: 50.284115,
								longitude: -113.427339,
								tags: [
									"dolor",
									"fugiat",
									"voluptate",
									"ipsum",
									"commodo",
									"ullamco",
									"excepteur",
								],
								friends: [
									{
										id: 0,
										name: "Dawn Britt",
									},
									{
										id: 1,
										name: "Miles Gross",
									},
									{
										id: 2,
										name: "Rachael Cantu",
									},
								],
								greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
								favoriteFruit: {
									_id: "67ec5ff72fc962d03a0a6299",
									index: 0,
									guid: "6a578650-cdd4-4e99-a5bb-27c892d8c474",
									isActive: true,
									balance: "$3,864.93",
									picture: "http://placehold.it/32x32",
									age: 39,
									eyeColor: "green",
									name: "Kerri Delaney",
									gender: "female",
									company: "PLASMOSIS",
									email: "kerridelaney@plasmosis.com",
									phone: "+1 (834) 413-3068",
									address: "310 Kings Hwy, Avoca, Virginia, 9799",
									about:
										"Dolore ullamco consequat magna ipsum laboris magna. Dolore adipisicing non consequat officia laboris excepteur elit. Lorem officia ea elit ea sunt ipsum elit. Do commodo ipsum consequat deserunt mollit enim excepteur magna nulla deserunt quis in qui.\r\n",
									registered: "2020-05-05T06:09:18 -03:00",
									latitude: 50.284115,
									longitude: -113.427339,
									tags: [
										"dolor",
										"fugiat",
										"voluptate",
										"ipsum",
										"commodo",
										"ullamco",
										"excepteur",
									],
									friends: [
										{
											id: 0,
											name: "Dawn Britt",
										},
										{
											id: 1,
											name: "Miles Gross",
										},
										{
											id: 2,
											name: "Rachael Cantu",
										},
									],
									greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
									favoriteFruit: "banana",
								},
							},
						},
					],
					greeting: "Hello, Kerri Delaney! You have 2 unread messages.",
					favoriteFruit: "banana",
				},
			},
		},
	},
	null,
	2,
);
