export const routes = {
	home: {
		rootPath: "/",
		name: "Главная",
		disabled: false,
		showInNavbar: true,
		subRoutes: {},
	},
	entityPreview: {
		name: "Просмотр сущности",
		rootPath: "/entity/:entityId",
		disabled: false,
		showInNavbar: false,
	},
	snapshots: {
		name: "Реестр снепшотов",
		rootPath: "/snapshots",
		disabled: false,
		showInNavbar: true,
	},
	jsonData: {
		name: "JSON Реестр",
		rootPath: "/json-data",
		disabled: false,
		showInNavbar: true,
	},
	allCommits: {
		name: "Реестр коммитов",
		rootPath: "/all-commits",
		disabled: false,
		showInNavbar: true,
	},
	objects: {
		name: "Объекты данных",
		rootPath: "/objects",
		disabled: false,
		showInNavbar: true,
	},
	objectCard: {
		name: "Карточка объекта",
		rootPath: "/objects/:objectId",
		disabled: false,
		showInNavbar: false,
	},
	models: {
		name: "Модели",
		rootPath: "/models",
		disabled: false,
		showInNavbar: true,
	},
	processes: {
		name: "Процессы",
		rootPath: "/processes",
		disabled: false,
		showInNavbar: true,
	},
	processGraph: {
		name: "Граф объектов",
		rootPath: "/processes/:processId/graph",
		disabled: false,
		showInNavbar: false,
	},
	commitQueue: {
		name: "Очередь коммитов",
		rootPath: "/commit-queue",
		disabled: true,
		showInNavbar: false,
	},
	changelog: {
		name: "История изменений",
		rootPath: "/changelog",
		disabled: false,
		showInNavbar: true,
	},
	changelogTable: {
		name: "История изменений V2",
		rootPath: "/changelog-table",
		disabled: false,
		showInNavbar: true,
		devOnly: false,
	},
	graphChangelog: {
		name: "История графика",
		rootPath: "/changelog/:graphId",
		disabled: false,
		showInNavbar: false,
	},
	// dev
	playground: {
		name: "Песочница",
		rootPath: "/playground",
		devOnly: true,
		disabled: false,
		showInNavbar: true,
	},
	swagger: {
		name: "API Документация",
		rootPath: "/swagger",
		devOnly: true,
		disabled: false,
		showInNavbar: true,
	},
};
